### ISSUE TITLE
Running spirals/parsec-3.0 on Kubernetes cluster

### ISSUE THREAD

**Issue by pritam27** [Spirals-Team/benchmark-containers#25]
I am trying to run the spirals/parsec-3.0 image as a pod on Kubernetes cluster referring to https://gist.github.com/balajismaniam/fac7923f6ee44f1f36969c29354e3902

I my case, I am trying with a manifest like this,

```
apiVersion: v1
kind: Pod
metadata:
  name: parsec-pod
spec:
  containers:
  - image: spirals/parsec-3.0
    command: ["/bin/bash"]
    args: ["parsecmgmt -r run -p canneal -i simsmall"]
    name: parsec-ctn
  restartPolicy: "Never"
```

However, when I run get pod,

```
NAME         READY   STATUS              RESTARTS   AGE
parsec-pod   0/1     ContainerCreating   0          6s
parsec-pod   0/1     Error               0          8s
parsec-pod   0/1     Error               0          10s
```
Here are the event logs,

```
Events:
  Type    Reason          Age    From               Message
  ----    ------          ----   ----               -------
  Normal  Scheduled       5m28s  default-scheduler  Successfully assigned default/parsec-pod to ocp410-24nts-worker-rbv46
  Normal  AddedInterface  5m29s  multus             Add eth0 [10.128.2.251/23] from openshift-sdn
  Normal  Pulling         5m29s  kubelet            Pulling image "spirals/parsec-3.0:latest"
  Normal  Pulled          5m23s  kubelet            Successfully pulled image "spirals/parsec-3.0:latest" in 5.930295127s
  Normal  Created         5m23s  kubelet            Created container parsec-ctn
  Normal  Started         5m23s  kubelet            Started container parsec-ctn
```
@mcolmant @gfieni @rouvoy , could you please point out what I am doing wrong here. Any suggestion would be greatly appreciated.

**Comment by pritam27** [comment]
The following manifest works,
```
apiVersion: v1
kind: Pod
metadata:
  name: parsec-pod
spec:
  containers:
  - image: spirals/parsec-3.0
    args: ["-a", "run", "-p", "canneal", "-i", "simsmall", "-S", "parsec"]
    name: parsec-ctn
  restartPolicy: "Never"
```
It seems that we just need to pass the arguments and there is no need for entering the container shell.
